In [9]:
#pandas
import pandas as pd
#creating series
marks=pd.Series([85,87,93,92,88,90])
print(marks)
marks=pd.Series([85,87,93,92,88,90],
               index=["riya","priya","divya","kavya","niya","shiv"])
print(marks)

0    85
1    87
2    93
3    92
4    88
5    90
dtype: int64
riya     85
priya    87
divya    93
kavya    92
niya     88
shiv     90
dtype: int64

In [10]:
#creating dataframe
data={
    "name":["suryabhan","madravati","vijaypal","anjali","sayali","shivtej"],
    "age":[76,72,46,42,18,15],
    "gender":["male","female","male","female","female","male"]
}
df=pd.DataFrame(data)
print(df)

        name  age  gender
0  suryabhan   76    male
1  madravati   72  female
2   vijaypal   46    male
3     anjali   42  female
4     sayali   18  female
5    shivtej   15    male

In [14]:
df.head()

        name  age  gender
0  suryabhan   76    male
1  madravati   72  female
2   vijaypal   46    male
3     anjali   42  female
4     sayali   18  female

In [15]:
df.tail(3)

      name  age  gender
3   anjali   42  female
4   sayali   18  female
5  shivtej   15    male

In [18]:
df.shape

(6, 3)

In [19]:
df.columns

Index(['name', 'age', 'gender'], dtype='object')

In [20]:
df.rename(columns={"name":"f_members"})

   f_members  age  gender
0  suryabhan   76    male
1  madravati   72  female
2   vijaypal   46    male
3     anjali   42  female
4     sayali   18  female
5    shivtej   15    male

In [21]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   age     6 non-null      int64
 2   gender  6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [22]:
df.describe()

             age
count   6.000000
mean   44.833333
std    25.802455
min    15.000000
25%    24.000000
50%    44.000000
75%    65.500000
max    76.000000

In [29]:
#save the file to csv
df.to_csv("family_details.csv",index=False)

In [30]:
pd.read_csv("family_details.csv")

        name  age  gender
0  suryabhan   76    male
1  madravati   72  female
2   vijaypal   46    male
3     anjali   42  female
4     sayali   18  female
5    shivtej   15    male

In [31]:
#import an excel file as csv
df=pd.read_csv(r"C:\Users\Sayali\OneDrive\student.csv")
print(df)

   roll_no      name  sgpa  cgpa
0       15     sayli  9.45  9.35
1       20     divya  9.80  9.60
2        5  pranjali  9.40  9.30
3        7    siddhi  9.20  9.00
4        3     anuja  9.00  8.90
5       11     aarya  9.10  9.00

In [36]:
df[["name"]]  #row selection

       name
0     sayli
1     divya
2  pranjali
3    siddhi
4     anuja
5     aarya

In [35]:
df.loc[df.name=="sayli"] #selection of specific row

   roll_no   name  sgpa  cgpa
0       15  sayli  9.45  9.35